"""Markdown exporter.

Produces a portable, paste-friendly ``.md`` file. The output is a
numbered list where each step is a heading + screenshot reference,
following GitHub-flavoured Markdown so it renders cleanly in tickets,
wikis, PR descriptions, and most note-taking apps.

Like the HTML exporter, screenshots are staged into a sibling
``<destination>-assets/`` folder so the Markdown file is portable
together with its images. When a step has a UIA-resolved bounding rect,
the staged image is the same crop+highlight rendering used by the HTML
exporter — so a step that looks tight in HTML looks tight in Markdown.

Steps without a screenshot just appear as numbered text. Suppressed
steps are omitted. The ``evidentiary`` flag is not filtered on here —
that's the report builder's job; this exporter shows the full draft.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from inscription.export._common import (
    build_event_resolver,
    select_primary_event,
    stage_step_asset,
)
from inscription.model import ExportDocument, utcnow
from inscription.util import format_clock_time

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

    from inscription.model import (
        DraftStep,
        RawEvent,
        ResolvedElement,
        ScreenshotArtifact,
        Session,
    )
    from inscription.storage import SessionRepository

logger = logging.getLogger(__name__)


def export_markdown(
    repository: SessionRepository,
    *,
    destination: Path | None = None,
) -> ExportDocument:
    """Render the session as Markdown."""
    session = repository.session
    steps = repository.list_steps()
    screenshots = {s.id: s for s in repository.list_screenshots() if s.id is not None}
    events_by_id: dict[int, RawEvent] = {
        e.id: e for e in repository.list_events() if e.id is not None
    }

    if destination is None:
        destination = session.exports_dir / f"{session.root.name}.md"
    destination.parent.mkdir(parents=True, exist_ok=True)
    assets_dir = destination.parent / f"{destination.stem}-assets"
    assets_dir.mkdir(exist_ok=True)

    resolve = build_event_resolver(repository)

    parts = [_render_header(session)]
    for i, step in enumerate(steps, start=1):
        parts.append(
            _render_step(
                index=i,
                step=step,
                screenshots=screenshots,
                events_by_id=events_by_id,
                resolver=resolve,
                session_root=session.root,
                assets_dir=assets_dir,
                assets_dirname=assets_dir.name,
            )
        )
    parts.append(_render_footer(session))

    destination.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    logger.info("Exported %s to %s", session.info.name, destination)

    return ExportDocument(
        session_name=session.info.name,
        format="markdown",
        path=destination,
        generated_at=utcnow(),
    )


# -------------------------------------------------------------- rendering


def _render_header(session: Session) -> str:
    info = session.info
    started = info.started_at.strftime("%Y-%m-%d %H:%M")
    ended = info.ended_at.strftime("%Y-%m-%d %H:%M") if info.ended_at else "in progress"
    return f"# {info.name}\n\n*Recorded {started} - {ended}*"


def _render_footer(session: Session) -> str:
    version = session.info.recorder_version or "unknown"
    return f"---\n\n*Generated by Inscription (recorder {version}).*"


def _render_step(
    *,
    index: int,
    step: DraftStep,
    screenshots: dict[int, ScreenshotArtifact],
    events_by_id: dict[int, RawEvent],
    resolver: Callable[[RawEvent], ResolvedElement | None],
    session_root: Path,
    assets_dir: Path,
    assets_dirname: str,
) -> str:
    action_text = step.action.strip() or "_(empty step)_"
    primary = select_primary_event(step, events_by_id)
    timestamp = format_clock_time(primary.occurred_at) if primary is not None else None
    heading = f"## Step {index}"
    if timestamp:
        heading = f"{heading} — {timestamp}"
    sections = [heading, action_text]
    if step.result.strip():
        sections.append(f"> **Result:** {step.result.strip()}")
    body = "\n\n".join(sections)
    shot = screenshots.get(step.screenshot_id) if step.screenshot_id else None
    if shot is None:
        return body
    element = resolver(primary) if primary else None
    asset_name = stage_step_asset(
        step=step,
        shot=shot,
        primary_event=primary,
        element=element,
        session_root=session_root,
        assets_dir=assets_dir,
    )
    if asset_name is None:
        return body
    alt = step.action.replace("\n", " ").replace("[", "(").replace("]", ")")[:120]
    image_md = f"![{alt}]({assets_dirname}/{asset_name})"
    return f"{body}\n\n{image_md}"


