"""Markdown exporter.

Produces a portable, paste-friendly ``.md`` file. The output is a
numbered list where each step is a heading + screenshot reference,
following GitHub-flavoured Markdown so it renders cleanly in tickets,
wikis, PR descriptions, and most note-taking apps.

Like the HTML exporter, screenshots are staged into a sibling
``<destination>-assets/`` folder so the Markdown file is portable
together with its images. When a step has a UIA-resolved bounding rect,
the staged image is the same crop+highlight rendering used by the HTML
exporter — so a step that looks tight in HTML looks tight in Markdown.

Steps without a screenshot just appear as numbered text. Suppressed
steps are omitted. The ``evidentiary`` flag is not filtered on here —
that's the report builder's job; this exporter shows the full draft.
"""

from __future__ import annotations

import logging
import shutil
from typing import TYPE_CHECKING

from inscription.model import ExportDocument, utcnow
from inscription.render import crop_highlight

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

    from inscription.model import (
        DraftStep,
        RawEvent,
        ResolvedElement,
        ScreenshotArtifact,
        Session,
    )
    from inscription.storage import SessionRepository

logger = logging.getLogger(__name__)


def export_markdown(
    repository: SessionRepository,
    *,
    destination: Path | None = None,
) -> ExportDocument:
    """Render the session as Markdown."""
    session = repository.session
    steps = repository.list_steps()
    screenshots = {s.id: s for s in repository.list_screenshots() if s.id is not None}
    events_by_id: dict[int, RawEvent] = {
        e.id: e for e in repository.list_events() if e.id is not None
    }

    if destination is None:
        destination = session.exports_dir / f"{session.root.name}.md"
    destination.parent.mkdir(parents=True, exist_ok=True)
    assets_dir = destination.parent / f"{destination.stem}-assets"
    assets_dir.mkdir(exist_ok=True)

    element_cache: dict[int, ResolvedElement | None] = {}

    def resolve(event: RawEvent) -> ResolvedElement | None:
        eid = event.resolved_element_id
        if eid is None:
            return None
        if eid not in element_cache:
            element_cache[eid] = repository.get_resolved_element(eid)
        return element_cache[eid]

    parts = [_render_header(session)]
    for i, step in enumerate(steps, start=1):
        parts.append(
            _render_step(
                index=i,
                step=step,
                screenshots=screenshots,
                events_by_id=events_by_id,
                resolver=resolve,
                session_root=session.root,
                assets_dir=assets_dir,
                assets_dirname=assets_dir.name,
            )
        )
    parts.append(_render_footer(session))

    destination.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    logger.info("Exported %s to %s", session.info.name, destination)

    return ExportDocument(
        session_name=session.info.name,
        format="markdown",
        path=destination,
        generated_at=utcnow(),
    )


# -------------------------------------------------------------- rendering


def _render_header(session: Session) -> str:
    info = session.info
    started = info.started_at.strftime("%Y-%m-%d %H:%M")
    ended = info.ended_at.strftime("%Y-%m-%d %H:%M") if info.ended_at else "in progress"
    return f"# {info.name}\n\n*Recorded {started} - {ended}*"


def _render_footer(session: Session) -> str:
    version = session.info.recorder_version or "unknown"
    return f"---\n\n*Generated by Inscription (recorder {version}).*"


def _render_step(
    *,
    index: int,
    step: DraftStep,
    screenshots: dict[int, ScreenshotArtifact],
    events_by_id: dict[int, RawEvent],
    resolver: Callable[[RawEvent], ResolvedElement | None],
    session_root: Path,
    assets_dir: Path,
    assets_dirname: str,
) -> str:
    text = step.text.strip() or "_(empty step)_"
    body = f"## Step {index}\n\n{text}"
    shot = screenshots.get(step.screenshot_id) if step.screenshot_id else None
    if shot is None:
        return body
    primary = _primary_event(step, events_by_id)
    element = resolver(primary) if primary else None
    asset_name = _stage_step_asset(
        step=step,
        shot=shot,
        primary_event=primary,
        element=element,
        session_root=session_root,
        assets_dir=assets_dir,
    )
    if asset_name is None:
        return body
    alt = step.text.replace("\n", " ").replace("[", "(").replace("]", ")")[:120]
    image_md = f"![{alt}]({assets_dirname}/{asset_name})"
    return f"{body}\n\n{image_md}"


def _primary_event(step: DraftStep, events_by_id: dict[int, RawEvent]) -> RawEvent | None:
    """Mirror the HTML exporter's primary-event selection."""
    for eid in step.source_event_ids:
        event = events_by_id.get(eid)
        if event is None:
            continue
        if step.screenshot_id is not None and event.screenshot_id == step.screenshot_id:
            return event
    for eid in step.source_event_ids:
        event = events_by_id.get(eid)
        if event is not None:
            return event
    return None


def _stage_step_asset(
    *,
    step: DraftStep,
    shot: ScreenshotArtifact,
    primary_event: RawEvent | None,
    element: ResolvedElement | None,
    session_root: Path,
    assets_dir: Path,
) -> str | None:
    src_path = session_root / shot.relative_path
    step_id = step.id if step.id is not None else step.sequence
    target = assets_dir / f"step-{step_id:05d}.png"

    try:
        raw_bytes = src_path.read_bytes()
    except OSError as exc:
        logger.warning("Could not read source screenshot %s: %s", src_path, exc)
        return None

    rect = element.bounding_rect if element is not None else None
    click = (
        (primary_event.x, primary_event.y)
        if primary_event is not None and primary_event.x is not None and primary_event.y is not None
        else None
    )

    if rect is None:
        try:
            shutil.copyfile(src_path, target)
        except OSError as exc:
            logger.warning("Could not stage asset %s: %s", src_path, exc)
            return None
        return target.name

    rendered = crop_highlight(raw_bytes, bounding_rect=rect, click_point=click)
    target.write_bytes(rendered)
    return target.name
