"""PDF export for forensic notes.

Wraps the existing forensic-notes HTML renderer and converts the
result to a PDF with per-page header (case + examiner) and footer
(generated timestamp + page X of Y) drawn over every page. Premium
feel for a courtroom / discovery deliverable: the operator hands
over a single self-contained file rather than an HTML directory
with assets.

Implementation: render the forensic-notes HTML to a temporary
directory (which writes its image-asset siblings alongside), load
it into a :class:`QTextDocument`, and walk the document page-by-page
through a :class:`QPrinter` set to PDF output. The header / footer
bands are drawn over each page by a :class:`QPainter` after the
document content is laid in.
"""

from __future__ import annotations

import logging
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from PySide6.QtCore import QMarginsF, QRectF, QSizeF, Qt, QUrl
from PySide6.QtGui import QFont, QPainter, QTextDocument
from PySide6.QtPrintSupport import QPrinter

from inscription.export.forensic import export_forensic_notes
from inscription.model import ExportDocument, utcnow

if TYPE_CHECKING:
    from inscription.storage import SessionRepository

logger = logging.getLogger(__name__)

#: Reserved space at the top of every printed page for the header
#: band (case + examiner). Millimeters; converted to device pixels at
#: render time using the printer's resolution.
_HEADER_HEIGHT_MM = 14.0

#: Reserved space at the bottom for the footer band (timestamp +
#: page numbers).
_FOOTER_HEIGHT_MM = 10.0

#: Outer page margins around the header / footer / body area.
_PAGE_MARGIN_TOP_MM = 12.0
_PAGE_MARGIN_BOTTOM_MM = 12.0
_PAGE_MARGIN_LEFT_MM = 18.0
_PAGE_MARGIN_RIGHT_MM = 18.0


def export_pdf(
    repository: SessionRepository,
    *,
    destination: Path,
    examiner: str | None = None,
    case_reference: str | None = None,
) -> ExportDocument:
    """Render the session's forensic notes to a self-contained PDF.

    ``examiner`` and ``case_reference`` show up both in the document's
    header block (page 1, generated by the forensic notes renderer)
    and in the per-page header band drawn over every printed page.
    """
    destination.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="inscription-pdf-") as tmpdir_str:
        tmpdir = Path(tmpdir_str)
        html_path = tmpdir / "notes.html"
        export_forensic_notes(
            repository,
            destination=html_path,
            examiner=examiner,
            case_reference=case_reference,
        )
        html_text = html_path.read_text(encoding="utf-8")
        session_name = repository.session.info.name
        _render_html_to_pdf(
            html_text=html_text,
            base_url=tmpdir,
            destination=destination,
            session_name=session_name,
            examiner=examiner,
            case_reference=case_reference,
        )
        logger.info(
            "Exported forensic-notes PDF for %s to %s", session_name, destination
        )

    return ExportDocument(
        session_name=repository.session.info.name,
        format="forensic-notes-pdf",
        path=destination,
        generated_at=utcnow(),
    )


def _render_html_to_pdf(
    *,
    html_text: str,
    base_url: Path,
    destination: Path,
    session_name: str,
    examiner: str | None,
    case_reference: str | None,
) -> None:
    """Page-by-page render of ``html_text`` to ``destination``.

    ``base_url`` is the directory the HTML's relative image paths
    resolve against (the temp dir the forensic-notes renderer wrote
    its assets into). Setting it on the QTextDocument makes
    ``<img src="notes-assets/...">`` references find the file on disk.
    """
    printer = QPrinter(QPrinter.PrinterMode.HighResolution)
    printer.setOutputFormat(QPrinter.OutputFormat.PdfFormat)
    printer.setOutputFileName(str(destination))
    layout = printer.pageLayout()
    layout.setUnits(layout.Unit.Millimeter)
    layout.setMargins(
        QMarginsF(
            _PAGE_MARGIN_LEFT_MM,
            _PAGE_MARGIN_TOP_MM,
            _PAGE_MARGIN_RIGHT_MM,
            _PAGE_MARGIN_BOTTOM_MM,
        )
    )
    printer.setPageLayout(layout)

    # The full paintable area on each page (paper minus printer margins),
    # in device pixels at the printer's resolution. We then carve out a
    # header band at the top and a footer band at the bottom and lay
    # the document into the band that's left.
    paint_rect = printer.pageRect(QPrinter.Unit.DevicePixel)
    px_per_mm = printer.resolution() / 25.4  # 25.4 mm per inch
    header_h_px = _HEADER_HEIGHT_MM * px_per_mm
    footer_h_px = _FOOTER_HEIGHT_MM * px_per_mm
    body_top = paint_rect.top() + header_h_px
    body_bottom = paint_rect.bottom() - footer_h_px
    body_height = body_bottom - body_top

    doc = QTextDocument()
    # The base URL has to be a "directory URL" (trailing slash) so
    # ``<img src="notes-assets/foo.png">`` in the HTML resolves to
    # ``<base>/notes-assets/foo.png`` rather than the parent.
    doc.setBaseUrl(QUrl.fromLocalFile(str(base_url) + "/"))
    doc.setHtml(html_text)
    doc.setPageSize(QSizeF(paint_rect.width(), body_height))

    page_count = max(1, doc.pageCount())
    timestamp = utcnow().strftime("%Y-%m-%d %H:%M UTC")

    painter = QPainter(printer)
    try:
        for page_idx in range(page_count):
            if page_idx > 0:
                printer.newPage()

            # Header band -- case + examiner on every page so a printed
            # page that gets separated from the rest still identifies
            # its source.
            _draw_header_band(
                painter,
                rect=QRectF(
                    paint_rect.left(),
                    paint_rect.top(),
                    paint_rect.width(),
                    header_h_px,
                ),
                session_name=session_name,
                examiner=examiner,
                case_reference=case_reference,
            )

            # Document body for this page. drawContents takes a rect in
            # document coordinates; we translate the painter so that the
            # current page's slice lands inside the body band, and clip
            # so a tall row at the bottom of one page doesn't bleed into
            # the next.
            painter.save()
            painter.setClipRect(
                QRectF(paint_rect.left(), body_top, paint_rect.width(), body_height)
            )
            painter.translate(0, body_top - page_idx * body_height)
            doc_page_rect = QRectF(
                0, page_idx * body_height, paint_rect.width(), body_height
            )
            doc.drawContents(painter, doc_page_rect)
            painter.restore()

            # Footer band: generated-at timestamp + page numbers.
            _draw_footer_band(
                painter,
                rect=QRectF(
                    paint_rect.left(),
                    body_bottom,
                    paint_rect.width(),
                    footer_h_px,
                ),
                page=page_idx + 1,
                page_count=page_count,
                timestamp=timestamp,
            )
    finally:
        painter.end()


def _draw_header_band(
    painter: QPainter,
    *,
    rect: QRectF,
    session_name: str,
    examiner: str | None,
    case_reference: str | None,
) -> None:
    """Draw the per-page header: title left, case/examiner right.

    A faint baseline rule under the band gives the printed page a
    "real document" feel without being visually heavy.
    """
    painter.save()
    try:
        # Title: session name, left-aligned.
        title_font = QFont()
        title_font.setBold(True)
        title_font.setPointSizeF(11)
        painter.setFont(title_font)
        painter.setPen(Qt.GlobalColor.black)
        title_rect = QRectF(rect.left(), rect.top(), rect.width() * 0.55, rect.height())
        painter.drawText(
            title_rect,
            int(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter),
            session_name,
        )

        # Right-aligned: examiner | case reference, one or both.
        meta_parts = [
            v for v in (examiner, case_reference) if v and v.strip()
        ]
        if meta_parts:
            meta_font = QFont()
            meta_font.setPointSizeF(9)
            painter.setFont(meta_font)
            meta_rect = QRectF(
                rect.left() + rect.width() * 0.45,
                rect.top(),
                rect.width() * 0.55,
                rect.height(),
            )
            painter.drawText(
                meta_rect,
                int(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter),
                "  ·  ".join(meta_parts),
            )

        # Faint separator rule along the bottom of the band.
        pen = painter.pen()
        pen.setColor(Qt.GlobalColor.gray)
        pen.setWidthF(0.5)
        painter.setPen(pen)
        painter.drawLine(
            int(rect.left()),
            int(rect.bottom()),
            int(rect.right()),
            int(rect.bottom()),
        )
    finally:
        painter.restore()


def _draw_footer_band(
    painter: QPainter,
    *,
    rect: QRectF,
    page: int,
    page_count: int,
    timestamp: str,
) -> None:
    """Draw the per-page footer: generated-at left, page X of Y right."""
    painter.save()
    try:
        # Faint separator rule along the top of the band.
        pen = painter.pen()
        pen.setColor(Qt.GlobalColor.gray)
        pen.setWidthF(0.5)
        painter.setPen(pen)
        painter.drawLine(
            int(rect.left()),
            int(rect.top()),
            int(rect.right()),
            int(rect.top()),
        )

        font = QFont()
        font.setPointSizeF(8)
        painter.setFont(font)
        painter.setPen(Qt.GlobalColor.darkGray)

        left_rect = QRectF(
            rect.left(),
            rect.top(),
            rect.width() * 0.6,
            rect.height(),
        )
        painter.drawText(
            left_rect,
            int(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter),
            f"Generated {timestamp}",
        )

        right_rect = QRectF(
            rect.left() + rect.width() * 0.4,
            rect.top(),
            rect.width() * 0.6,
            rect.height(),
        )
        painter.drawText(
            right_rect,
            int(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter),
            f"Page {page} of {page_count}",
        )
    finally:
        painter.restore()
